"""your new changes

Revision ID: b76ebae5b120
Revises: b389592974f8
Create Date: 2025-10-18 05:51:12.560302

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "b76ebae5b120"
down_revision: Union[str, None] = "b389592974f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
